### PR TITLE
open links in new tab/window and load image urls

### LINKED ISSUE #911: Thumbnails only for images/ Url link for rest of file types
### Expected behavior
When files are received, the plateforme looks a lot more professional if they are displayed as thumbnails or at least icons instead of a long url link.

### Actual behavior

Except for images files received are displayed as url links including videos.

### Steps to reproduce the behavior
1.
2.
3.

### Environment
- **JSXC version:** 
- **Host system and version:** 
- **Browser vendor and version:** 
- **Any browser plugins enabled?** 
- **XMPP server vendor and version:** 
- **Is your XMPP server working with other clients as expected?** 
yes 

#### Javascript

```
```

#### JSXC

```
```

#### XMPP

```
```

#### Host

```
```

### PR DESCRIPTION
**Pull request by mightymop**
show image links as attachement and open links in new tab by setting target=_blank on links
fix #911
link1

### CODE REVIEW

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 1]
```diff
@@ -158,7 +158,7 @@ export default class HttpUploadPlugin extends AbstractPlugin {
 
       let html = $('<div>').append(message.getHtmlMessage());
 
-      let linkElement = $('<a>');
+      let linkElement = $('<a target="_blank">');
```
Comment (sualko) [inline src/plugins/httpUpload/HttpUploadPlugin.ts:161]: We need to add `rel="noopener noreferrer"` for privacy and security protection.

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 2]
```diff
@@ -227,6 +227,7 @@ export default class HttpUploadPlugin extends AbstractPlugin {
       let element = $(stanza);
       let bodyElement = element.find('html body[xmlns="' + Strophe.NS.XHTML + '"]').first();
       let dataElement = element.find('data[xmlns="urn:xmpp:bob"]');
+      let body = element.find('body');
```
Comment (sualko) [inline src/plugins/httpUpload/HttpUploadPlugin.ts:230]: That's to unspecific.

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 3]
```diff
@@ -254,6 +255,32 @@ export default class HttpUploadPlugin extends AbstractPlugin {
             }
          }
       }
+      else
+          if (body.length===1 && !message.isEncrypted())
+          {
+              var link = body.text();
```
Comment (sualko) [inline src/plugins/httpUpload/HttpUploadPlugin.ts:261]: Url with text will not be detected.

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 4]
```diff
@@ -254,6 +255,32 @@ export default class HttpUploadPlugin extends AbstractPlugin {
...
+                '((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|'+ // domain name
+                '((\\d{1,3}\\.){3}\\d{1,3}))'+ // OR ip (v4) address
+                '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ // port and path
+                '(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
+                '(\\#[-a-z\\d_]*)?$','i'); // fragment locator
+              if (!!pattern.test(link)&&link.lastIndexOf('.')>0)
+              {
+                   let suffix = link.substring(link.lastIndexOf('.')+1).toLowerCase();
+
+                   if (link.endsWith('.jpeg')||link.endsWith('.jpg')||link.endsWith('.png')||link.endsWith('.gif')||link.endsWith('.svg'))
```
Comment (sualko) [inline src/plugins/httpUpload/HttpUploadPlugin.ts:273]: could also be written as `['jpeg', ...].indexOf(suffix) > -1`.

**Review by sualko — CHANGES_REQUESTED** [review]
This PR will introduce some privacy issues, because it automatically loads external content. We would need a "load image" button with some information about the implications and a configurable allow list for trusted domains.

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 4 above)
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:273]: changed...

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 3 above)
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:261]: is see jsxc will send urls with text in the following format:
url\ntext...
Now this will be parsed too.
Furthermore urls with example: http://domain:port/image.jpg?parameter... parameters will be parsed correctly too

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 2 above)
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:230]: now using element.children('body') to get the body tag...

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 1 above)
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:161]: added

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 2 above)
Comment (sualko) [reply src/plugins/httpUpload/HttpUploadPlugin.ts]: There can also be multiple body children in XMPP. Just use the `message.getPlaintext()` method.

**Review by sualko — CHANGES_REQUESTED** [review]
Without an opt-in option to load images, this pr can't be merged.

**Comment by mightymop** [comment]
> 
> 
> Without an opt-in option to load images, this pr can't be merged.

So first showing a generic image as thumbnail with the ability to download is better? and furthermore a whitelist of allowed domains in settings!?

**Comment by sualko** [comment]
> So first showing a generic image as thumbnail with the ability to download is better? and furthermore a whitelist of allowed domains in settings!?

That's right. Similar to email clients. Otherwise the user could be tracked.

**Comment by mightymop** [comment]
> 
> 
> > So first showing a generic image as thumbnail with the ability to download is better? and furthermore a whitelist of allowed domains in settings!?
> 
> That's right. Similar to email clients. Otherwise the user could be tracked.

I think the intention of the Issuer was the he wants to see the images without doing sth. lazyness/comfort i guess, so the automatic download of images is wanted.
But i would change it in that way that if a domain is on whitelist the images are going to be downloaded automatically and if not then generic picture will be shown and the user has to click to download.

**Comment by mightymop** [comment]
Settingsdialog now look like this:

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 5]
```diff
@@ -246,14 +290,86 @@ export default class HttpUploadPlugin extends AbstractPlugin {
...
             }
          }
       }
+      else
+          if (body.length===1 && !message.isEncrypted())
+          {
+              let link = body.text();
+              let bodyText = link;
+              //Check if in normal body tag is text after URL to show
+              if (bodyText.split('\n').length>0)
```
Comment (sualko) [inline src/plugins/httpUpload/HttpUploadPlugin.ts:332]: Why are we requiring a newline to display the image?

File: src/ui/dialogs/settings.ts [hunk 6]
```diff
@@ -37,15 +37,38 @@ class StartPage extends Page {
...
+         undefined,
+         undefined,
+         undefined,
+         undefined
+      ));
 
       contentElement.append(new ListItem(
          Translation.t('Language'),
-         Translation.t('After_changing_this_option_you_have_to_reload_the_page'),
+         undefined,
```
Comment (sualko) [inline src/ui/dialogs/settings.ts:50]: Why was this removed?

File: src/ui/dialogs/settings.ts [hunk 7]
```diff
@@ -37,15 +37,38 @@ class StartPage extends Page {
...
          undefined,
          undefined,
          this.getLanguageSelectionElement()
       ));
 
+      contentElement.append(new ListItem(
+         Translation.t('trusted_domains'),
```
Comment (sualko) [inline src/ui/dialogs/settings.ts:57]: I think for the user it's not obvious what a trusted domain is. We need an explanation.

File: src/ui/dialogs/settings.ts [hunk 8]
```diff
@@ -37,15 +37,38 @@ class StartPage extends Page {
...
+         Translation.t('one_domain_per_line'),
+         undefined,
+         undefined,
+         this.getTrustedDomainsElement()
+      ));
+
+	  contentElement.append(new ListItem(
```
Comment (sualko) [inline src/ui/dialogs/settings.ts:64]: Support for wildcards would be more flexibel. E.g. you could allow `*.data.foobar.com` and don't have to allow subdomains for every domain.

File: src/Attachment.ts [hunk 9]
```diff
@@ -101,6 +101,11 @@ export default class Attachment {
       this.properties.set('thumbnail', thumbnail);
    }
 
+   public setGenericThumbnail()
```
Comment (sualko) [inline src/Attachment.ts:104]: We probably don't need this method, because we will always use the same image as "generic thumbnail". This means we can easily test if it's used or not.

**Review by sualko — CHANGES_REQUESTED** [review]
This pr is a good starting point, but I think there are some things missing (which don't have to be implemented in this pr imo).

- loading thumbnail on user behalf
  - with explaination
  - with option to trust this domain in the future
- option to define a proxy to protect the users privacy

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 10]
```diff
@@ -223,10 +226,51 @@ export default class HttpUploadPlugin extends AbstractPlugin {
       return Promise.resolve([message, xmlStanza]);
    }
 
+   private extractDomainFromUrl(url) {
```
[the remark this answers is not in the document]
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:229]: 🤦‍♂️ i need some hollidays again :D i know..

File: src/ui/dialogs/settings.ts (hunk 6 above)
Comment (mightymop) [reply src/ui/dialogs/settings.ts:50]: just for design reasons but will revert it...

File: src/ui/dialogs/settings.ts (hunk 7 above)
Comment (mightymop) [reply src/ui/dialogs/settings.ts:57]: added further infos

File: src/ui/dialogs/settings.ts (hunk 8 above)
Comment (mightymop) [reply src/ui/dialogs/settings.ts:64]: wildcards added

File: src/Attachment.ts (hunk 9 above)
Comment (mightymop) [reply src/Attachment.ts:104]: removed... and set generic image as default..
this would be overwritten if used otherwise with an other thumbnail...

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 11]
```diff
@@ -246,14 +290,86 @@ export default class HttpUploadPlugin extends AbstractPlugin {
...
+
+               let domain = this.extractDomainFromUrl(url);
+               if (this.isTrustedDomain(domain))
+               {
+                  attachment.setThumbnailData(thumbnailData);
+               }
+               else
+               {
+                  attachment.setGenericThumbnail();
+               }
```
[the remark this answers is not in the document]
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:302]: ok

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 12]
```diff
@@ -246,14 +290,86 @@ export default class HttpUploadPlugin extends AbstractPlugin {
...
+                '(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
+                '(\\#[-a-z\\d_]*)?$','i'); // fragment locator
+              if (!!pattern.test(link)&&link.lastIndexOf('.')>0)
+              {
+                   if (link.indexOf('?') > -1)
+                   {
+                       link = link.substring(0,link.lastIndexOf('?'));
+                   }
+
+                   let suffix = link.substring(link.lastIndexOf('.')+1).toLowerCase();
```
[the remark this answers is not in the document]
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:352]: using now

File: src/plugins/httpUpload/HttpUploadPlugin.ts [hunk 13]
```diff
@@ -246,14 +290,86 @@ export default class HttpUploadPlugin extends AbstractPlugin {
...
+              let bodyText = link;
+              //Check if in normal body tag is text after URL to show
+              if (bodyText.split('\n').length>0)
+              {
+                  let bodyTextArr = body.text().split('\n');
+                  bodyTextArr[0]='';
+                  bodyText = bodyTextArr.map(item => item.trim()).join('\n').trim();
+              }
+
+              let pattern = new RegExp('^(https?:\\/\\/)?'+ // protocol
```
[the remark this answers is not in the document]
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:339]: ah you mean url ins textmessages embedded? hm I forgot this case... i only thought about uploading images .. but you are right... will change it..

[the remark this answers is not in the document]
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:339]: now extracting all URLs from messagetext and analyze them...
the first will become an attachment.. further links will become a clickable link...

File: src/plugins/httpUpload/HttpUploadPlugin.ts (hunk 5 above)
Comment (mightymop) [reply src/plugins/httpUpload/HttpUploadPlugin.ts:332]: i process all links now...

**Comment by sualko** [comment]
FYI I had to change a few things:

- links are already handled by jsxc, so no need to detect links twice (btw your implementation allowed xss)
- target blank was not needed at the second place, because the generated html is send to the peer and there is a very strict set of allowed attributes in xmpp
- only links at the beginning of the message are detected as attachment, because I don't want to alter the meaning of a message
- I added a placeholder image

One step further to create an awesome xmpp client. Thank you very much for your effort.

**Comment by mightymop** [comment]
i think #868 could be closed too?

**Comment by sualko** [comment]
> i think #868 could be closed too?

I think it's more about loading the image inside the ui/dialog. At least we should probably remove the `download` attribute from image links, so that the browser is not showing the download dialog.
